name: OpenCue Packaging Pipeline

# TODO Remove this comment, used to trigger github actions.

# Trigger this pipeline on new commits to master.
on:
  push:
    branches: [ more-release-pipeline ]

jobs:
  # TODO(https://github.com/AcademySoftwareFoundation/OpenCue/issues/715) Add the other
  #   packaging steps here. Things like building Docker images and extracting artifacts
  #   will need to be generalized, but we need to test a few things in the master branch
  #   first to make sure things are working as we expect.
  build_cuebot:
    name: Build Cuebot
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all Git history, otherwise the current version number will
          # not be correctly calculated.
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_REGION }}
          role-to-assume: ${{ secrets.AWS_S3_ROLE }}

      - name: Set build ID
        run: |
          set -e
          ci/generate_version_number.sh > VERSION
          echo "Build ID: $(cat ./VERSION)"
          echo "::set-env name=BUILD_ID::$(cat ./VERSION)"

      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          dockerfile: cuebot/Dockerfile
          repository: opencuebuild/cuebot
          tags: ${{ env.BUILD_ID }}

      - name: Extract Artifacts
        run: |
          set -e
          image_name="opencuebuild/cuebot:${BUILD_ID}"
          container_id=$(docker create ${image_name})
          artifacts="/opt/opencue/cuebot-${BUILD_ID}-all.jar /opt/opencue/opencue-cuebot-${BUILD_ID}-1.noarch.rpm"
          mkdir -p "${GITHUB_WORKSPACE}/artifacts/"
          for artifact in $artifacts; do
            docker cp ${container_id}:${artifact} "${GITHUB_WORKSPACE}/artifacts/"
          done
          docker rm $container_id

      - name: Upload Cuebot JAR
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 cp ${GITHUB_WORKSPACE}/artifacts/cuebot-${BUILD_ID}-all.jar s3://${S3_BUCKET}/opencue/${BUILD_ID}/cuebot-${BUILD_ID}-all.jar
