name: OpenCue Packaging Pipeline

# Trigger this pipeline on new commits to master.
on:
  push:
    branches: [ more-release-pipeline ]

jobs:
  # TODO(https://github.com/AcademySoftwareFoundation/OpenCue/issues/715) Add the other
  #   packaging steps here. Things like building Docker images and extracting artifacts
  #   will need to be generalized, but we need to test a few things in the master branch
  #   first to make sure things are working as we expect.

  build_component:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component: [cuebot, rqd]
        include:
          - component: cuebot
            NAME: Cuebot
            ARTIFACTS: cuebot-${BUILD_ID}-all.jar opencue-cuebot-${BUILD_ID}-1.noarch.rpm

          - component: rqd
            NAME: RQD
            ARTIFACTS: rqd-${BUILD_ID}-all.tar.gz

    name: Build ${{ matrix.NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all Git history, otherwise the current version number will
          # not be correctly calculated.
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_REGION }}
          role-to-assume: ${{ secrets.AWS_S3_ROLE }}
          role-duration-seconds: 1800

      - name: Set build ID
        run: |
          set -e
          ci/generate_version_number.sh > VERSION
          echo "Build ID: $(cat ./VERSION)"
          echo "::set-env name=BUILD_ID::$(cat ./VERSION)"

      - name: Build Docker image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
          dockerfile: ${{ matrix.component }}/Dockerfile
          repository: opencuebuild/${{ matrix.component }}
          tags: ${{ env.BUILD_ID }}

      - name: Extract Artifacts
        run: |
          set -e
          image_name="opencuebuild/${{ matrix.component }}:${BUILD_ID}"
          container_id=$(docker create ${image_name})
          artifacts="${{ matrix.ARTIFACTS }}"
          mkdir -p "${GITHUB_WORKSPACE}/artifacts/"
          for artifact in $artifacts; do
            docker cp ${container_id}:/opt/opencue/${artifact} "${GITHUB_WORKSPACE}/artifacts/"
          done
          docker rm $container_id

      - name: Upload Artifacts
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          artifacts="${{ matrix.ARTIFACTS }}"
          for artifact in $artifacts; do
            aws s3 cp ${GITHUB_WORKSPACE}/artifacts/${artifact} s3://${S3_BUCKET}/opencue/${BUILD_ID}/
          done

      - name: Display artifacts
        env:
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
        run: |
          aws s3 ls s3://${S3_BUCKET}/opencue/${BUILD_ID}/
